cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('', include('shop.urls'))
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(),name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(),name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(),name='order_validation'),
    path('complete/', order_complete,name='order_complete'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

order/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from coupon.models import Coupon
class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    coupon = models.ForeignKey(Coupon, on_delete=models.PROTECT, related_name='order_coupon', null=True, blank=True)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0),MaxValueValidator(100000)])

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_product(self):
        return sum(item.get_item_price() for item in self.items.all())

    def get_total_price(self):
        total_product = self.get_total_product()
        return total_product - self.discount


from shop.models import Product
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='order_products')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_item_price(self):
        return self.price * self.quantity

import hashlib
from .iamport import payments_prepare, find_transaction
class OrderTransactionManager(models.Manager):
    def create_new(self,order,amount,success=None,transaction_status=None):
        if not order:
            raise ValueError("주문 오류")

        order_hash = hashlib.sha1(str(order.id).encode('utf-8')).hexdigest()
        email_hash = str(order.email).split("@")[0]
        final_hash = hashlib.sha1((order_hash  + email_hash).encode('utf-8')).hexdigest()[:10]
        merchant_order_id = "%s"%(final_hash)

        payments_prepare(merchant_order_id,amount)

        tranasction = self.model(
            order=order,
            merchant_order_id=merchant_order_id,
            amount=amount
        )

        if success is not None:
            tranasction.success = success
            tranasction.transaction_status = transaction_status

        try:
            tranasction.save()
        except Exception as e:
            print("save error",e)

        return tranasction.merchant_order_id

    def get_transaction(self,merchant_order_id):
        result = find_transaction(merchant_order_id)
        if result['status'] == 'paid':
            return result
        else:
            return None


class OrderTransaction(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    merchant_order_id = models.CharField(max_length=120, null=True, blank=True)
    transaction_id = models.CharField(max_length=120, null=True,blank=True)
    amount = models.PositiveIntegerField(default=0)
    transaction_status = models.CharField(max_length=220, null=True,blank=True)
    type = models.CharField(max_length=120,blank=True)
    created = models.DateTimeField(auto_now_add=True,auto_now=False)

    objects = OrderTransactionManager()

    def __str__(self):
        return str(self.order.id)

    class Meta:
        ordering = ['-created']

def order_payment_validation(sender, instance, created, *args, **kwargs):
    if instance.transaction_id:
        import_transaction = OrderTransaction.objects.get_transaction(merchant_order_id=instance.merchant_order_id)

        merchant_order_id = import_transaction['merchant_order_id']
        imp_id = import_transaction['imp_id']
        amount = import_transaction['amount']

        local_transaction = OrderTransaction.objects.filter(merchant_order_id = merchant_order_id, transaction_id = imp_id,amount = amount).exists()

        if not import_transaction or not local_transaction:
            raise ValueError("비정상 거래입니다.")

# 결제 정보가 생성된 후에 호출할 함수를 연결해준다.
from django.db.models.signals import post_save
post_save.connect(order_payment_validation,sender=OrderTransaction)

order/forms.py
from django import forms

from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','email','address','postal_code','city']

order/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.cart import Cart
from .forms import *

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.amount
                order.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])

            cart.clear()
            return render(request, 'order/created.html', {'order':order})
    else:
        form = OrderCreateForm()
    return render(request, 'order/create.html', {'cart':cart, 'form':form})


from django.contrib.admin.views.decorators import staff_member_required
@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order/admin/detail.html', {'order':order})

# pdf를 위한 임포트
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string

@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('order/admin/pdf.html', {'order':order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=order_{}.pdf'.format(order.id)
    weasyprint.HTML(string=html).write_pdf(response, stylesheets=[weasyprint.CSS(settings.STATICFILES_DIRS[0]+'/css/pdf.css')])
    return response


# ajax로 결제 후에 보여줄 결제 완료 화면
def order_complete(request):
    order_id = request.GET.get('order_id')
    order = Order.objects.get(id=order_id)
    return render(request,'order/created.html',{'order':order})

# 결제를 위한 임포트
from django.views.generic.base import View
from django.http import JsonResponse

class OrderCreateAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated":False}, status=403)

        cart = Cart(request)
        form = OrderCreateForm(request.POST)

        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.amount
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            data = {
                "order_id": order.id
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)

# 결제 정보 생성
class OrderCheckoutAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated":False}, status=403)

        order_id = request.POST.get('order_id')
        order = Order.objects.get(id=order_id)
        amount = request.POST.get('amount')

        try:
            merchant_order_id = OrderTransaction.objects.create_new(
                order=order,
                amount=amount
            )
        except:
            merchant_order_id = None


        if merchant_order_id is not None:
            data = {
                "works": True,
                "merchant_id": merchant_order_id
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)

# 실제 결제가 이뤄진 것이 있는지 확인
class OrderImpAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated":False}, status=403)

        order_id = request.POST.get('order_id')
        order = Order.objects.get(id=order_id)
        merchant_id = request.POST.get('merchant_id')
        imp_id = request.POST.get('imp_id')
        amount = request.POST.get('amount')

        try:
            trans = OrderTransaction.objects.get(
                order=order,
                merchant_order_id=merchant_id,
                amount=amount
            )
        except:
            trans = None

        if trans is not None:
            trans.transaction_id = imp_id
            trans.success = True
            trans.save()
            order.paid = True
            order.save()

            data = {
                "works": True
            }

            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)

# Create your views here.

order/templates/order/create.html
{% extends 'base.html' %}

{% block title %}
Checkout
{% endblock %}

{% block script %}
<script type="text/javascript">
csrf_token = '{{ csrf_token }}';
order_create_url = '{% url "orders:order_create_ajax" %}';
order_checkout_url = '{% url "orders:order_checkout" %}';
order_validation_url = '{% url "orders:order_validation" %}';
order_complete_url = '{% url "orders:order_complete" %}';
</script>

<script src="https://cdn.iamport.kr/js/iamport.payment-1.1.5.js" type="text/javascript"></script>

{% load static %}
<script src="{% static 'js/checkout.js' %}" type="text/javascript"></script>

{% endblock %}

{% block content %}
<div class="row">
        <div class="col">
            <div class="alert alert-info" role="alert">
              Your Order
            </div>
    <ul class="list-group">
        {% for item in cart %}
            <li class="list-group-item">
                {{item.quantity}}X{{item.product.name}}
                <span>{{item.total_price}}</span>
            </li>
        {% endfor %}
        {% if cart.coupon %}
            <li class="list-group-item">

                    "{{ cart.coupon.code }}" ({{ cart.coupon.amount }}% off)

                <span>- ${{ cart.get_total_discount|floatformat:"2" }}</span>
            </li>
        {% endif %}
    </ul>
            <div class="alert alert-success" role="alert">Total : {{cart.get_total_price|floatformat:"2"}}</div>

    <!-- form에 class 추가 -->
    <form action="" method="post" class="order-form">
        {{form.as_p}}
        {% csrf_token %}
        <!-- hidden field 추가-->
        <input type="hidden" name="pre_order_id" value="0">
        <input type="hidden" name="amount" value="{{ cart.get_total_price|floatformat:'2' }}">
        <input type="submit" class="btn btn-primary float-right" value="Place Order">
    </form>
    </div>
    </div>
{% endblock %}

order/templates/order/order.html
{% extends 'base.html' %}

{% block title %}
Checkout
{% endblock %}

{% block script %}
<script type="text/javascript">
csrf_token = '{{ csrf_token }}';
order_create_url = '{% url "orders:order_create_ajax" %}';
order_checkout_url = '{% url "orders:order_checkout" %}';
order_validation_url = '{% url "orders:order_validation" %}';
order_complete_url = '{% url "orders:order_complete" %}';
</script>

<script src="https://cdn.iamport.kr/js/iamport.payment-1.1.5.js" type="text/javascript"></script>

{% load static %}
<script src="{% static 'js/checkout.js' %}" type="text/javascript"></script>

{% endblock %}

{% block content %}
<div class="row">
        <div class="col">
            <div class="alert alert-info" role="alert">
              Your Order
            </div>
    <ul class="list-group">
        {% for item in cart %}
            <li class="list-group-item">
                {{item.quantity}}X{{item.product.name}}
                <span>{{item.total_price}}</span>
            </li>
        {% endfor %}
        {% if cart.coupon %}
            <li class="list-group-item">

                    "{{ cart.coupon.code }}" ({{ cart.coupon.amount }}% off)

                <span>- ${{ cart.get_total_discount|floatformat:"2" }}</span>
            </li>
        {% endif %}
    </ul>
            <div class="alert alert-success" role="alert">Total : {{cart.get_total_price|floatformat:"2"}}</div>

    <!-- form에 class 추가 -->
    <form action="" method="post" class="order-form">
        {{form.as_p}}
        {% csrf_token %}
        <!-- hidden field 추가-->
        <input type="hidden" name="pre_order_id" value="0">
        <input type="hidden" name="amount" value="{{ cart.get_total_price|floatformat:'2' }}">
        <input type="submit" class="btn btn-primary float-right" value="Place Order">
    </form>
    </div>
    </div>
{% endblock %}

order/templates/order/ordered.html
{% extends 'base.html' %}

{% block title %}
Order Complete
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="alert alert-success" role="alert">Thank you!<br/>
            Your order has been successfully completed.<br/>
        Your order number is <strong>{{order.id}}</strong></div>

    </div>
</div>
{% endblock %}